// Explicit argument order for every runnable problem: PostgreSQL JSONB object key order is not a function signature.
// Adding a problem means adding its slug here, a JSON seed, and a trusted reference in scripts/lib/reference-library.ts
// (or scripts/lib/reference-expansion.ts for problems added after the first 35).
export const SIGNATURES: Record<string, { entryPoint: string; keys: string[] }> = {
  "relay-window": { entryPoint: "relayWindow", keys: ["loads", "width"] },
  "quiet-badge": { entryPoint: "quietBadge", keys: ["badges"] },
  "parcel-checkpoints": { entryPoint: "parcelCheckpoints", keys: ["parcels", "ranges"] },
  "dock-threshold": { entryPoint: "dockThreshold", keys: ["capacities", "load"] },
  "lantern-steps": { entryPoint: "lanternSteps", keys: ["costs"] },
  "ridge-count": { entryPoint: "ridgeCount", keys: ["heights"] },
  "ticket-pair": { entryPoint: "ticketPair", keys: ["prices", "budget"] },
  "mirror-callsign": { entryPoint: "mirrorCallsign", keys: ["text"] },
  "longest-clean-streak": { entryPoint: "longestCleanStreak", keys: ["log"] },
  "balanced-blueprint": { entryPoint: "balancedBlueprint", keys: ["plan"] },
  "warmer-wait": { entryPoint: "warmerWait", keys: ["temps"] },
  "ticket-turns": { entryPoint: "ticketTurns", keys: ["tickets", "position"] },
  "chain-loop-start": { entryPoint: "chainLoopStart", keys: ["next", "head"] },
  "balanced-canopy": { entryPoint: "balancedCanopy", keys: ["tree"] },
  "ledger-tree-check": { entryPoint: "ledgerTreeCheck", keys: ["tree"] },
  "splice-cables": { entryPoint: "spliceCables", keys: ["lengths"] },
  "grid-rescue-hops": { entryPoint: "gridRescueHops", keys: ["grid"] },
  "orchard-plots": { entryPoint: "orchardPlots", keys: ["grid"] },
  "cheapest-route": { entryPoint: "cheapestRoute", keys: ["stops", "roads", "start", "target"] },
  "crate-combinations": { entryPoint: "crateCombinations", keys: ["weights", "target"] },
  "watchtower-placements": { entryPoint: "watchtowerPlacements", keys: ["size"] },
  "fewest-tokens": { entryPoint: "fewestTokens", keys: ["tokens", "amount"] },
  "shared-melody": { entryPoint: "sharedMelody", keys: ["first", "second"] },
  "rising-marks": { entryPoint: "risingMarks", keys: ["marks"] },
  "charging-hops": { entryPoint: "chargingHops", keys: ["ranges"] },
  "bake-batches": { entryPoint: "bakeBatches", keys: ["trays", "days"] },
  "merge-shifts": { entryPoint: "mergeShifts", keys: ["shifts"] },
  "rank-tags": { entryPoint: "rankTags", keys: ["tags"] },
  "first-redundant-link": { entryPoint: "firstRedundantLink", keys: ["stations", "links"] },
  "task-order": { entryPoint: "taskOrder", keys: ["tasks", "prerequisites"] },
  "prefix-counts": { entryPoint: "prefixCounts", keys: ["words", "queries"] },
  "lone-sensor": { entryPoint: "loneSensor", keys: ["readings"] },
  "prime-tally": { entryPoint: "primeTally", keys: ["limit"] },
  "lru-results": { entryPoint: "lruResults", keys: ["capacity", "operations"] },
  "gutter-capacity": { entryPoint: "gutterCapacity", keys: ["heights"] },
  // Library expansion batch 1 (trusted references in scripts/lib/reference-expansion.ts).
  "studio-bookings": { entryPoint: "studioBookings", keys: ["bookings"] },
  "slot-insert": { entryPoint: "slotInsert", keys: ["slots", "newSlot"] },
  "prefix-suggestions": { entryPoint: "prefixSuggestions", keys: ["words", "typed"] },
  "radio-clusters": { entryPoint: "radioClusters", keys: ["towers", "links"] },
  "module-plan": { entryPoint: "modulePlan", keys: ["modules", "prerequisites"] },
  "lit-panels": { entryPoint: "litPanels", keys: ["count"] },
  "tile-side": { entryPoint: "tileSide", keys: ["planks"] },
  "kth-badge": { entryPoint: "kthBadge", keys: ["tree", "k"] },
  "canopy-layers": { entryPoint: "canopyLayers", keys: ["tree"] },
  "dial-lookup": { entryPoint: "dialLookup", keys: ["dial", "target"] },
  "fuel-stretch": { entryPoint: "fuelStretch", keys: ["fuel", "target"] },
  "postfix-ledger": { entryPoint: "postfixLedger", keys: ["tokens"] },
  "floor-tracker": { entryPoint: "floorTracker", keys: ["operations"] },
};
