import type { Snapshot } from "./contracts";
import type { QuestionKind } from "@/generated/prisma/client";
type Question = { id: string; kind: QuestionKind; difficulty: "EASY" | "MEDIUM" | "HARD"; topic: string; snapshot: Snapshot };
const question = (id: string, kind: QuestionKind, topic: string, title: string, statement: string, reference: string): Question => ({ id, kind, topic, difficulty: "EASY", snapshot: { version: 1, title, statement, details: "Explain your reasoning, discuss costs or tradeoffs, and give a concrete check or example.", reference, revision: null, slug: null } });
export const INTERVIEW_QUESTIONS: Question[] = [
  question("collection-membership", "CONCEPTUAL", "hash-maps", "Workshop Check-In Index", "A workshop checks whether each arriving badge ID is on a registration list. Compare scanning the list for every arrival with building a hash set once. Explain duplicate IDs, expected time, worst-case qualifications and extra memory.", "A list scan costs O(n) per arrival, or O(nm) for m arrivals. Building a hash set takes expected O(n) time and O(n) extra memory; m membership checks take expected O(m). Duplicates collapse if only membership matters. Hash performance depends on the implementation and collisions; expected constant time is not a universal worst-case guarantee. Test registered, missing and repeated IDs."),
  question("last-crate", "DEBUGGING", "arrays", "The Missing Final Crate", "A depot counts positive crate weights using: let count = 0; for (let i = 0; i < weights.length - 1; i++) { if (weights[i] > 0) count++; } return count; Find the defect, propose the smallest correction, and describe tests that would catch it.", "The loop excludes the last index. Use i < weights.length. With [4] the faulty loop returns 0 instead of 1; [0, 3] isolates a positive final element. Also test [], all nonpositive values and multiple positives. A full scan costs O(n) time and O(1) extra space."),
  question("repeated-ledger", "OPTIMIZATION", "arrays", "Repeated Depot Totals", "An immutable ledger has n signed changes. A service answers q half-open range-sum requests by scanning each requested range. Propose a faster design for many requests, explain its cost, and describe what changes if ledger entries can be edited frequently.", "Use n+1 prefix totals with prefix[0]=0; answer [a,b) with prefix[b]-prefix[a]. Preprocessing takes O(n), each query O(1), and extra memory O(n), for O(n+q) total. Frequent point updates make rebuilding expensive; discuss a Fenwick tree or segment tree with O(log n) update/query costs. Check empty ranges, negative values and an end equal to n."),
  question("handoff-decision", "BEHAVIORAL", "design", "A Handoff Under Pressure", "A teammate asks you to merge a feature shortly before a demo, but you find an untested failure case. Describe how you would communicate the issue, decide what to ship, and follow up. Use a real experience if you have one; otherwise clearly label a hypothetical response.", "Describe the situation and your responsibility, then the specific risk and evidence. Offer proportionate choices such as a fix with a focused check, a reduced demo scope or a rollback plan. Explain whom you involve, how you avoid blame, and how you document the decision. Conclude with the outcome or expected outcome and a follow-up improvement. Do not invent a personal achievement."),
  question("study-room-booking", "SYSTEM_DESIGN", "design", "Campus Study Room Booking", "Sketch a small campus room-booking service. Students browse availability and reserve one room for a time interval. Explain the data model, how you prevent overlapping reservations during concurrent requests, and how you handle retries. Start with one campus rather than global scale.", "Clarify interval boundaries, cancellations and identity. Model rooms, users and bookings; validate times and authorization on the server. A database exclusion constraint on room/time ranges, or a transaction with appropriate locking, prevents concurrent overlaps; an availability check alone is insufficient. Use an idempotency key for retries. Index lookup paths, return conflicts clearly and test two competing reservations, touching intervals and canceled bookings."),
];
